<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
  <meta charset="UTF-8">
  <title>ุฌุงุฆุฒุฉ ุฃูุถู ุฃููู ูุนุงู 2025</title>
  <style>
    body {
      background-color: #f2f2f2;
      font-family: 'Tahoma', sans-serif;
      text-align: center;
      padding: 30px;
    }
    .anime {
      margin: 30px auto;
      background: white;
      border-radius: 12px;
      padding: 20px;
      width: 80%;
      box-shadow: 0 0 10px rgba(0,0,0,0.1);
    }
    .anime img {
      width: 250px;
      border-radius: 8px;
    }
    .button {
      margin-top: 15px;
      padding: 10px 30px;
      font-size: 18px;
      background-color: #004080;
      color: white;
      border: none;
      border-radius: 6px;
      cursor: pointer;
    }
    .results, .reveal, iframe {
      display: none;
      margin-top: 20px;
    }
    .results p {
      font-size: 20px;
    }
    .reveal {
      font-size: 30px;
      color: red;
      font-weight: bold;
      margin-top: 50px;
    }
  </style>
</head>
<body>

  <h1>๐ฉ๐ฟ ูุฒุงุฑุฉ ุงูุซูุงูุฉ ุงูุฌุฒุงุฆุฑูุฉ - ุงุณุชุจูุงู ุฑุณูู ูุฃูุถู ุฃููู ูุนุงู 2025</h1>

  <!-- ุฃููู Attack on Titan -->
  <div class="anime">
    <h2>Attack on Titan</h2>
    <img src="https://upload.wikimedia.org/wikipedia/en/7/70/Attack_on_Titan_cover.jpg" alt="Attack on Titan">
    <br>
    <button class="button" onclick="voteReal()">ุตููุช ุงูุขู</button>
  </div>

  <!-- ุฃููู One Piece -->
  <div class="anime">
    <h2>One Piece</h2>
    <img src="https://upload.wikimedia.org/wikipedia/en/6/65/One_Piece_Logo.png" alt="One Piece">
    <br>
    <button class="button" onclick="voteFake('One Piece')">ุตููุช ุงูุขู</button>
  </div>

  <!-- ุฃููู Steins;Gate -->
  <div class="anime">
    <h2>Steins;Gate</h2>
    <img src="https://upload.wikimedia.org/wikipedia/en/b/b5/Steins_Gate.jpg" alt="Steins Gate">
    <br>
    <button class="button" onclick="voteFake('Steins;Gate')">ุตููุช ุงูุขู</button>
  </div>

  <!-- ูุชุงุฆุฌ ุญููููุฉ -->
  <div class="results" id="realResults">
    <p>๐ธ Attack on Titan: 45%</p>
    <p>๐ธ One Piece: 35%</p>
    <p>๐ธ Steins;Gate: 20%</p>
  </div>

  <!-- ูุชุงุฆุฌ ูุฒููุฉ -->
  <div class="results" id="fakeResults">
    <p id="fake1"></p>
    <p id="fake2"></p>
    <p id="fake3"></p>
  </div>

  <!-- ุงูุฎุฏุนุฉ -->
  <div class="reveal" id="reveal">
    ๐ ุชู ุฎุฏุงุนู ูุฌุฏุฏูุง ูุง ุตุงุญุจ ุงูุนูู ุงูุตุบูุฑ!<br>
    <span style="font-size: 24px;">- ุฃุญูุฏ (ุงููุฑุฉ ุงูุฎุงูุณุฉ ูุงูุทูู)</span>
    <br><br>
    <img src="https://i.pinimg.com/originals/35/39/0e/35390e58aa216a6c41d3b29eeb99750a.gif" alt="Aizen Laughing" width="300">
    <br>
    <iframe src="https://www.youtube.com/embed/5xvbE3zdtmE?autoplay=1" width="300" height="200" allow="autoplay" title="ุถุญูุฉ ุฃูุฒู"></iframe>
  </div>

  <!-- ุงูููุงู -->
  <div style="text-align: right; direction: rtl; margin-top: 60px; background: #ffffff; padding: 20px; border-radius: 10px; box-shadow: 0 0 10px rgba(0,0,0,0.1); font-size: 16px; line-height: 1.9;">
    <h2 style="color: #004080;">๐ ูุจุฐุฉ ุนู ุฃููู "Attack on Titan"</h2>
    <p>
      ููุนุฏ ุฃููู "ูุฌูู ุงูุนูุงููุฉ" ูู ุฃุจุฑุฒ ุงูุฃุนูุงู ุงููููุฉ ุงููุงุจุงููุฉ ุงูุชู ุญููุช ุตุฏูู ุนุงููููุง ูุงุณุนูุงุ ููุง ูุญููู ูู ุนูู ุฏุฑุงูู ูุฅุณูุงุทุงุช ุณูุงุณูุฉ ูุงุฌุชูุงุนูุฉ ุฌุฑูุฆุฉุ ูุฃุณููุจ ุจุตุฑู ูุฐูู.
    </p>
    <p>
      ุชุฏูุฑ ุงููุตุฉ ูู ุนุงูู ูุนูุด ููู ุงูุจุดุฑ ุฏุงุฎู ุฃุณูุงุฑ ุถุฎูุฉ ุชุญูููู ูู ุชูุฏูุฏ ุฎุงุฑุฌู ูุฑุนุจ: ุงูุนูุงููุฉ. ุชุจุฏุฃ ุงููุตุฉ ุจุงุฎุชุฑุงู ุฃุญุฏ ุงูุฃุณูุงุฑุ ุญูุซ ูุดูุฏ "ุฅูุฑูู" ููุชู ูุงูุฏุชูุ ูุง ูุฏูุนู ูุจุฏุก ุฑุญูุชู ุงูุงูุชูุงููุฉ.
    </p>
    <p>
      ุชุชุทูุฑ ุงููุตุฉ ูุงุญููุง ุจุดูู ููุงุฌุฆุ ูุชุชุญูู ุฅูู ุตุฑุงุน ุจูู ุงูุฃูุฏููููุฌูุงุชุ ูุชูุดู ุนู ูุคุงูุฑุงุช ุฏูููุฉ ูุญูุงุฆู ูุฎููุฉ ุญูู ุฃุตู ุงูุนูุงููุฉ ูุงูุญุถุงุฑุงุช ุงููุฎุชููุฉ.
    </p>
    <p>
      ุชุชููุฒ ุงูุณูุณูุฉ ุจููุณููุงูุง ุงูุชุตููุฑูุฉ ุงูููุญููุฉ ูุซู "Treachery" ู"Call of Silence"ุ ูุจุดุฎุตูุงุช ูุนูุฏุฉ ุชููุฏ ุงููุตุฉ ูุซู ูููุงูุ ุฒููุ ูุฃุฑููู.
    </p>
    <p>
      ูุนุชุจุฑู ุงููุซูุฑูู ุฃุนุธู ุฃููู ูู ุงูุชุงุฑูุฎุ ููุง ููู ูู ูุงูุนูุฉ ูุงุชูุฉ ูุทุฑุญ ููุณูู ุนููู.
    </p>
    <p style="font-weight: bold; margin-top: 30px; font-size: 18px;">๐จ ููุงุญุธุฉ: ุงูุชุตููุช ุญูููู ููุชู ุงุนุชูุงุฏู ูู ูุจู ูุฌูุฉ ุงูุฃููู ุงููุทููุฉ.</p>
  </div>

  <!-- ุณูุฑุจุช -->
  <script>
    function voteReal() {
      document.getElementById('realResults').style.display = 'block';
      setTimeout(() => {
        document.getElementById('reveal').style.display = 'block';
        document.querySelector('iframe').style.display = 'block';
      }, 2500);
    }

    function voteFake(name) {
      let percentages = {
        "Attack on Titan": "45%",
        "One Piece": "30%",
        "Steins;Gate": "25%"
      };

      // ุชุญุฏูุซ ุงููุชุงุฆุฌ ุญุณุจ ุงูุงุฎุชูุงุฑ ุงููุฒูู
      document.getElementById('fake1').textContent = "๐ธ Attack on Titan: " + percentages["Attack on Titan"];
      document.getElementById('fake2').textContent = "๐ธ One Piece: " + percentages["One Piece"];
      document.getElementById('fake3').textContent = "๐ธ Steins;Gate: " + percentages["Steins;Gate"];

      document.getElementById('fakeResults').style.display = 'block';

      setTimeout(() => {
        document.getElementById('reveal').style.display = 'block';
        document.querySelector('iframe').style.display = 'block';
      }, 2500);
    }
  </script>

</body>
</html>
